export const LOAD_BREWERIES_SUCCESS = 'LOAD_BREWERY_SUCCESS';
export const EDIT_BREWERY = 'EDIT_BREWERY';
export const ADD_BREWERY = 'ADD_BREWERY';
export const UPDATE_BREWERY = 'UPDATE_BREWERY';
export const DELETE_BREWERY = 'DELETE_BREWERY';
